name: Cache Node and NPM Dependes
description: This action allows to cache both node and npm dependencies based on lock.json

inputs:
    node-version:
        description: NodeJS Version
        default: 20.x
        required: true
    working-dir:
        description: The working directolry of the application
        default: '.'
        required: false
runs:
    using: composite
    steps:
        - name: Setup Node Version ${{ inputs.node-version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{inputs.node-version}}
        - name: Cached dependencies
          id: cache
          uses: actions/cache#v3
          with:
            path: ${{inputs. working-dir}}/node_modules
            key: node_modules-${{hashFiles('${{inputs.working-dir}}/package-lock.json')}}
        - name: Install dependencies
          if:  steps.cache.outputs.cache-hit != 'true'
          run: npm ci
          shell: bash
          working-directory: $${{inputs.working-dir}}

             
