name: 02 workflow events
on: 
  push:
  pull_request:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: echo "run by ${{github.event_name}}"
