name: 03 - Workflow Runner
on: push
jobs:
  ubuntu-echo:
      runs-on: ubuntu-latest
      steps:
        - name: Show OS
          run: |
            echo "This is running on Ubuntu"
            echo "runner os $RUNNER_OS"
  windows-echo:
      runs-on: windows-latest
      steps:
        - name: Show OS
          run: |
            echo "This is running on windows"
            echo "runner os $RUNNER_OS"
