name: 04 Using Actions
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    # 0. Checkout the code from the repo
    # 1. Setup Node
    # 2. Install Dependencies
    # 3. Run Unit test
    steps:
      - name: Checkoout Code
        uses: actions/checkout@v4
      - name: Print Folders
        run: ls
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '16.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit test
        run: npm run test
        
