name: 08 Using Variables
on:
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: " i am workflow env"
    OVERITTEN: " workflow overwritten"
    UNDEFINED: ${{vars.UNDEFINE || 'undefine'}}
jobs:
    echo:
        runs-on: ubuntu-latest
        env: 
            JOB_VAR: " i am job env"
            OVERITTEN: "over written in job level"
        steps:
            - name: Print Env variables
              env:
                STEP_VAR: "I am a step env"
              run: |
                echo "step var ${{env.STEP_VAR}}"
                echo "step var ${{env.JOB_VAR}}"
                echo "step var ${{env.WORKFLOW_VAR}}"
                echo "step var ${{env.OVERITTEN}}"
            - name: Overwritten
              env:
                OVERITTEN: "over written in job other step"
              run: |
                echo "step var ${{env.OVERITTEN}}"
    echo2:
        runs-on: ubuntu-latest
        steps:
            - name: Print vars
              run: |
                echo "org var ${{var.ORG_VAR}}"
                echo "org var ${{var.OVERRITTEN_VAR}}"
                echo "rpo var ${{var.MY_VAR}}"
    echo-prod:
        runs-on: ubuntu-latest
        environment: Prod
        steps:
            - name: Print ENVs
              run: |
                echo "org var ${{var.TARGET_VAR}}"
                echo "org var ${{var.OVERWRITTEN_VAR}}"
    echo-undefined:
        runs-on: ubuntu-latest
        environment: Prod
        steps:
            - name: Print ENVs
              run: |
                    echo "org var ${{env.UNDEFINED"}}"

