name: 08 Using Variables
on:
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: " i am workflow env"
    OVERITTEN: " workflow overwritten"
jobs:
    echo:
        runs-on: ubuntu-latest
        env: 
            JOB_VAR: " i am job env"
            OVERITTEN: "over written in job level"
        steps:
            - name: Print Env variables
              env:
                STEP_VAR: "I am a step env"
              run: |
                echo "step var ${{env.STEP_VAR}}"
                echo "step var ${{env.JOB_VAR}}"
                echo "step var ${{env.WORKFLOW_VAR}}"
                echo "step var ${{env.OVERITTEN}}"
            - name: Overwritten
              env:
                OVERITTEN: "over written in job other step"
              run: |
                echo "step var ${{env.OVERITTEN}}"
