name: 10 Controllling the execution flow
on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: wheather unit test pass or not
                default: true
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: lint and build
              run: echo "lint and build"
    unit-tests:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
        - name: running unit tests
          run: echo "running tests"
        - name: failing tests
          if: ${{ !inputs.pass-unit-tests }}
          run: exit 1

    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-tests
        steps:
            - name: deploy nonprod
              run: echo "deploying nonprod"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-nonprod
        steps:
            - name: e2e tests
              run: echo "e2e tests"
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: load tests
              run: echo "load tests"
    deploy-prod:
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
            - load-tests
        steps:
            - name: deploy to prod
              run: echo "deploy to prod"