name: 11 Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: skip deployment and only print build output
                default: false
            target:
                type: environment
                required: true
                description: which envirnment the workflow will target
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: which env workflow use

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "buidling tag ${{ inputs.tag }}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{!inputs.dry-run}}
        environment: ${{ inputs.target }}
        needs: build
        steps:
            - name: Build
              run: echo "buidling tag ${{ inputs.target }}"