name: 12 Working With Outputs
on: 
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - fail
                default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
        steps:
            - name: Build
              id: build
              run: echo "status=success" >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: deploy
              run: echo "Deploying...."