name: 14 Artificats
on:
    workflow_dispatch:

env:
    build-artifact-key: app-${{github.sha}}
    test-report-key: test-coverage-${{github.sha}}
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Steup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Download Cached Dependencies
              uses: actions/cache@v3
              id: cache
              with:
                path: 14-artifiacts/react-app/node_modules
                key: deps-node-modules-${{hashFiles('14-artifacts/react-app/package.json')}}
            - name: Install Deps
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Unit tests
              run: npm run test -- --coverage
            - name: upload tests
              uses: actions/upload-artifact@v3
              with:
                name: ${{env.test-report-key}}
                path: 14-artifacts/react-app/coverage
            - name: build code
              run: npm run build
            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                name: ${{env.build-artifact-key}}
                path: 14-artifacts/react-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: ${{env.build-artifact-key}}
                path: build
            - name: show folder
              run: ls -R
        



