name: 15 Metrices
on:
    workflow_dispatch:
jobs:
    backward_compactability:
        name: ${{matrix.os}} - ${{matrix.node-version}}
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
        steps:
            - name: Steup node
              uses: actions/steup-node@v3
              with: ${{matrix.node-version}}
            - name: Perform Tests
              run: echo "Running Test ${{matrix.os}} and node ${{matrix.node-version}}"