name: 15 Metrices
on:
    workflow_dispatch:
jobs:
    backward_compactability:
        name: ${{matrix.os}} - ${{matrix.node-version}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include: 
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: Steup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{matrix.node-version}}
            - name: fail if experiemtal
              if: matrix.tag == 'experimental'
              run: exit 1
            - name: Perform Tests
              run: |
                echo "Running Test ${{matrix.os}} and node ${{matrix.node-version}}"
                sleep 10
            - name: Upload tests
              run: echo "uploading tests"
    include-example:
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: [red, green]
                shape: [ciccle, square]
                size: [small, large]
                include: 
                    - color: red
                      shape: triange
