name: 16 Enviornaments
run-name: 16 - Env | env - ${{inputs.target-env}}
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: echo vars
              run: |
                echo "env: ${{env.my-env-value}}"